version: '3.8'

services:
  mongo_db:
    container_name: database_container
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_db:/data/db

  app:
    build: .
    ports:
      - 3000:3000
    environment:
      - MONGODB_URI=mongodb+srv://ganesh:gani@cluster0.y1gbwmy.mongodb.net/blog
      - JWT_SECRET=MySecretBlog
    depends_on:
      - mongo_db

volumes:
  mongo_db:
